name: weather_app
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies: 
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0